### ISSUE TITLE
ROS 2 IDL tutorial

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/examples#133]
**Context:**
[ROS 2 interface definition](http://design.ros2.org/articles/interface_definition.html) has more features than the ROS 1 one. A tutorial showing all the possibilities of this new interface doesn’t exist yet.

**Task:**
- [ ] Create an ament package containing
  - [ ] msg files covering all the IDL features
    - [ ] Add comment next to each field explaining the functionality
  - [ ] Source code (C++ and Python) showing how to set and get values for all these message fields
- [ ] Create a Tutorial on the [ROS 2 wik](https://github.com/ros2/ros2/wiki/Tutorials)i walking the users through the IDL features in ROS 2, using the sample msg files and the associated code

**Pointers:**
The message files used for testing [here](https://github.com/ros2/system_tests/tree/master/test_communication/msg) and [here](https://github.com/ros2/rosidl/tree/master/rosidl_generator_py/msg) can be used as a starter and extended accordingly

**Comment by mikaelarguedas** [comment]
moved to https://github.com/ros2/tutorials/issues/1
